### ISSUE TITLE
Avoid flashing

### ISSUE THREAD

**Issue by goldbergyoni** [rickhanlonii/jest-silent-reporter#17]
I really believe in this reporter - while coding, a developer needs a piece of mind and not tons of log entries.

Is there a way to take it a step further - avoid the terminal flashing/refreshing anytime the tests run? whenever the tests run, the terminal always updates itself with some default watcher message, can this be eliminated to make it even more quiet?

**Comment by jjolmo** [comment]
Would be great to have a way to not show absolute anything unless a jest test crashes, even a way to hide the "Test Passed" string

**Comment by rickhanlonii** [comment]
@jjolmo that's a great feature request, could you submit a new issue?

**Comment by rickhanlonii** [comment]
@goldbergyoni I think the flashing happens from inside Jest, I don't think the reporter has the ability to avoid it. Going to close this for now, but if anyone finds a way to do it then I'm happy to review a PR!
