### ISSUE TITLE
Option for console.error warnings

### ISSUE THREAD

**Issue by schinery** [rickhanlonii/jest-silent-reporter#25]
After upgrading Formik in a project that doesn't use this reporter I noticed that I was getting warnings that were using `console.error` instead of `console.warn`, and so weren't outputted when `showWarnings` is set to true.

```sh
console.error
      Warning: An update to Formik inside a test was not wrapped in act(...).
```

Would it be possible to add `entry.type === 'error'` to the console filtering check for warnings?

**Comment by rickhanlonii** [comment]
Added, thanks for the PR!

**Comment by schinery** [comment]
Nice one! Already have the 0.5.0 version installed and working 👍🏻
