### ISSUE TITLE
Readme images not working

### ISSUE THREAD

**Issue by pipedreambomb** [rickhanlonii/jest-silent-reporter#27]
If you look at the readme at https://github.com/rickhanlonii/jest-silent-reporter, none of the images load.

**Comment by sibelius** [comment]
can we move this images to this repo?

**Comment by waldyrious** [comment]
If someone is able to dig up a copy of the images, I'd be happy to submit a PR replacing the images in the README. Unfortunately I wasn't able to find an archived version of these images.

**Comment by rickhanlonii** [comment]
Fixed, sorry I stopped using Cloudapp pro 👍
