### ISSUE TITLE
Add an option to keep the final report

### ISSUE THREAD

**Issue by Asaf-S** [rickhanlonii/jest-silent-reporter#28]
Hey, great package. Can you add an option to keep the final report (see image below)?
It will be hard to keep track of the amount of many failures and it's not that verbose.

![image](https://user-images.githubusercontent.com/10521803/126907327-850d04d6-06f7-42bd-9c12-5237f335842d.png)

**Comment by Asaf-S** [comment]
If Facebook will approve my [PR](https://github.com/facebook/jest/pull/11695), then I'll make a PR here as well.

**Comment by Asaf-S** [comment]
A bit overdue, but finally done.
Please merge the following PR: #29.
I tested it, and it works fine.

**Comment by rickhanlonii** [comment]
Commented on the PR, thanks!
