### ISSUE TITLE
Usage Example of CLI

### ISSUE THREAD

**Issue by MdNaushad** [rickhanlonii/jest-silent-reporter#33]
Hey Great Repo,!!

I am trying to use CLI to set up the `jest-silent-reporter`, but the configuration options are not getting set. 

If I try it this way 
`jest --config jest.config.js --reporters=jest-silent-reporter JEST_SILENT_REPORTER_SHOW_WARNINGS=true`
It fails with error 
```
Error: Could not resolve a module for a custom reporter.
Module name: JEST_SILENT_REPORTER_SHOW_WARNINGS=true
```

if I try it this way 
`jest --config jest.config.js --reporters=jest-silent-reporter --JEST_SILENT_REPORTER_SHOW_WARNINGS=true`

The command works, but no warnings are shown, same behavior I have noticed for JEST_SILENT_REPORTER_SHOW_DOTS

Can you please add some more examples to your read me for usages of the env variables?

**Comment by MdNaushad** [comment]
I have used the following 
`cross-env JEST_SILENT_REPORTER_DOTS=true` and this seem to work, is this the correct way of passing the env variables?

**Comment by SimenB** [comment]
On Windows, yes. For Mac/Linux you don't need `cross-env`. You can also use WSL
