### ISSUE TITLE
Windows 10 & powershell jest 29.7.0 + "@swc/jest": "^0.2.29" silent reporter not picked up

### ISSUE THREAD

**Issue by agenteo** [rickhanlonii/jest-silent-reporter#36]
Hey there,

thanks heaps for creating this plugin, from the bottom of my heart and my eyes (crying over scrolling jest' default output).

Sadly it doesn't work for me. All I see is my regular jest output. I am on windows 10, my app uses:
    "jest": "^29.7.0",
    "jest-silent-reporter": "^0.5.0",

All I get is this:

❯ npx jest --reporters=jest-silent-reporter src
Error: Could not resolve a module for a custom reporter.
  Module name: src

I tried to put src at the front which doesn't even mention the "could not resolve".

In both cases I get my regular jest output.

Any tips on how to fix this? Cheers

**Comment by rickhanlonii** [comment]
The error message makes me think it's reading the src arg as the reporter value instead of jest-silent-reporter. This is because the --arg=value isn't valid syntax, at least with whatever Jest uses to parse args. 

Can you try removing the "=" and using a space instead, as in

`npx jest --reporters jest-silent-reporter src`

I think this would work too:

`npx jest reporters=jest-silent-reporter src`

**Comment by agenteo** [comment]
npx jest reporters=jest-silent-reporter src picks up the whole as a pattern:
![image](https://github.com/rickhanlonii/jest-silent-reporter/assets/16841/2a55a581-cf40-481f-a50e-00f39b4b8c52)

No luck with

❯ npx jest --reporters jest-silent-reporter src
Error: Could not resolve a module for a custom reporter.
  Module name: src
    at C:\Users\e\workspace\k\node_modules\jest-config\build\normalize.js:426:15
    at Array.map (<anonymous>)
    at normalizeReporters (C:\Users\e\workspace\k\node_modules\jest-config\build\normalize.js:409:20)
    at C:\Users\e\workspace\k\node_modules\jest-config\build\normalize.js:747:17
    at Array.reduce (<anonymous>)
    at normalize (C:\Users\e\workspace\k\node_modules\jest-config\build\normalize.js:608:14)
    at readConfig (C:\Users\e\workspace\k\node_modules\jest-config\build\index.js:160:74)
    at async readConfigs (C:\Users\e\workspace\k\node_modules\jest-config\build\index.js:424:26)
    at async runCLI (C:\Users\e\workspace\k\node_modules\@jest\core\build\cli\index.js:151:59)
    at async Object.run (C:\Users\e\workspace\k\node_modules\jest-cli\build\run.js:130:37)

**Comment by agenteo** [comment]
[CLOSED BY MISTAKE]

~Got it:~
`npx jest --reporters\=jest-silent-reporter src`

~I have the POWERshell 🤦‍♂️~

UPDATE 1:
Nope still failing... And it's doesn't seem to be a powershell issue.

When I pass a random report name it fails...

```
❯ npx jest --reporters=pizza src
Error: Could not resolve a module for a custom reporter.
  Module name: pizza

```

UPDATE2:
I created an empty jest test, and it works
`jest --reporters=jest-silent-reporter`
But when I run on the folder with tests:
`jest --reporters=jest-silent-reporter test`

it breaks with the message discussed above.

```
Error: Could not resolve a module for a custom reporter.
  Module name: test
```

UPDATE3:

`npx jest --reporters=jest-silent-reporter -- test`

fixes it in the test code, but in the real app (I already tried that) and it fails to pickup the reporter and just runs my tests:

```
❯ npx jest --reporters=jest-silent-reporter -- src

  ● ResidencyCalculator › when clicked on the Next button › should swap the selectbox for static text

    RangeError: End Date is invalid
```
UPDATE4:

I found the root cause, my project uses swc-jest ("@swc/jest": "^0.2.29") vs the test project I created has ts-jest

Any tips? Thanks!

**Comment by SimenB** [comment]
>This is because the --arg=value isn't valid syntax, at least with whatever Jest uses to parse args

It's perfectly valid, but `--reporters` takes an array, so any subsequent options are also fed into it.

https://github.com/yargs/yargs/blob/e517318cea0087b813f5de414b3cdec7b70efe33/docs/api.md#array

>When the option is used with a positional, use `--` to tell `yargs` to stop adding values to the array.

---

Alternative is just to flip the order: `npx jest src --reporters thing`. If that doesn't work, it's indeed a powershell thing. Maybe use WSL? I highly doubt usage of swc impacts this one way or the other
