### ISSUE TITLE
Missing newline while using dot output

### ISSUE THREAD

**Issue by henryruhs** [rickhanlonii/jest-silent-reporter#5]
Hey,

using `JEST_SILENT_REPORTER_DOTS=true` is causing something like:

```
......................foo@bar:~/WebstormProjects/jest$
```

instead of:

```
......................

foo@bar:~/WebstormProjects/jest$
```

**Comment by SimenB** [comment]
Should be a simple fix, I'm sure Rick would appreciate a PR :D

**Comment by henryruhs** [comment]
Yeah, something like that in `SilentReporter.js`:

```js
  onRunComplete() {
    if (this.useDots) {
      this.stdio.log('\n');
    }
    this.stdio.close();
  }
```

Via pull request https://github.com/rickhanlonii/jest-silent-reporter/pull/6
