### ISSUE TITLE
Option to output warnings

### ISSUE THREAD

**Issue by binkley** [rickhanlonii/jest-silent-reporter#7]
As part of cleaning out "cruft" in our tests, and sometimes problems in our production code, I want to *NOT* see:

1. Progress messages -- ✔

And want to *DO* see:

2. Test failures -- ✔
3. Warnings (from node or react, etc.) -- ✘

This reporter is exactly what I need for (1) and (2), however, also suppresses warning for (3).

----

Feature request for an option not to suppress warning messages as tests run, to only suppress the progress-style messages.

**Comment by rickhanlonii** [comment]
Hey @binkley, great feature request, I'll look into adding this 👍

**Comment by binkley** [comment]
@rickhanlonii Thank you!
